### PR TITLE
Game interface

### PR DESCRIPTION
**Pull request by aldemeery**
### Added
- Essential dependencies for interface styling.
- Basic interface.
- A cool logo.
- A `cls` method to clear the command line interface.
- `Player` class.
- `Game` class.

### CODE REVIEW

**Comment by aldemeery** [comment]
Changees have been implemented

**Comment by aldemeery** [comment]
### FOR WHOEVER IS GOING TO BE REVIEWING THE PR
Please note that this PR is about the Game interface, it doesn't have anything to do with the logic of the game. That's why when trying out the game right now you will always get `No one is winning` at the end of the game, even if one player should be winning

**Comment by aldemeery** [comment]
@mikenath223 **I can't believe you didn't even check the code thoroughly and yet you rejected the PR, and carelessly wasting a complete day of waiting for us.**

Regarding the points you mentioned:
 > Please take note that your loop in bin/main.rb is expected to have an exit condition, at the present state your loop would run forever, kindly set an exit condition on the loop based on the game conditions, perhaps winner, loser or draw.

  Here is the break point (line 46 at `bin/main.rb`):
 `break if command == :q # Players still want to quit, let's break out the game loop.`

---

> At each turn you should display which player has the turn.

If you have run the code, or just looked at it you would see line 78 at `lib/game.rb`
`next_move = @prompt.ask("#{current_player.display_name} (1..#{@dimension**2}): ") do |q|`
 
---

> Also at the end of a turn you are expected to indicate if that turn resulted in a winner or loser.

Again, if you have run the code, or just looked at it, you would see line 55 at `lib/game.rb`
`draw_box((winner.display_name + ' is the winner! Hurray!!').colorize(:blue), { width: 50 })`

**All the points this PR is rejected for are already there**
This is actually the worst review I have ever received.

**Comment by mikenath223** [comment]
Hi @aldemeery
Kindly note that the line `break if command == :q` is not the right exit condition as the game shouldn't end based on just the player input but rather it should depend on the outcome of the game either there is a winner or a tie.
In addition you were asked to make contact on slack if you needed further clarifications please take note of this in future PR.

**Comment by aldemeery** [comment]
Changes introduced here are being introduced by #5, thus, closing this PR

**Pull request closed without merging**
