### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by aldemeery**
### Added

- The game logic.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @aldemeery and @emasdev  :clap:  :clap:  :clap:  :clap:  :clap:  :clap:  :clap:  :clap:  :clap:  :clap:
##### You did an excellent job. However, you have a few changes to implement before the project can be approved.

**_1. No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))_**

**_Fix the required changes and submit for review._**

**_Overall you did a good job._**

#### _Reviewed by Temitayo Adeleke_

**Comment by aldemeery** [comment]
Changes implemented.

**Comment by aldemeery** [comment]
Issues Fixed

**Comment by aldemeery** [comment]
Closing

**Pull request closed without merging**
